#!/usr/bin/env python3
# Generates hsr_renderer_cpp/src/cook/embedded_assets.{h,cpp} so the cook is STANDALONE:
# every required asset (cooker/*.bin templates + the Nuxd.apk donor files) is baked into the binary.
# The donor = Nuxd minus scene.zip / AndroidManifest (replaced at cook time) / META-INF / params SKIP list.
import os, sys, zlib, zipfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))   # repo root
OUT  = os.path.join(ROOT, "hsr_renderer_cpp", "src", "cook")
NUXD = os.path.join(ROOT, "Envs To check", "v203 Ufficial Envs", "Nuxd.apk")

# The 16 static templates the cook reads via readFileBytes("cooker/...").
COOKER_FILES = [
    "flipbook.surface.bin","flipbook_mat.bin","nuxd_unlit_shader.bin","nuxd_unlitblend_shader.bin",
    "realdome_mat.bin","realfloor_mat.bin","realfloor_phys.bin","ref_skinned_mesh.bin",
    "skinned_mat.bin","skinned_mat_v2.bin","unlitblendskinned.bin","unlitdoublesidedskinned.bin",
    "vat_mat.bin","vat_shader.bin","vatunlitblend.surface.bin","wispscale.surface.bin",
]
# nuxd donor: everything spliceAPK keeps (scene.zip + AndroidManifest are replaced; META-INF + these are dropped).
NUXD_DROP = {"assets/scene.zip","AndroidManifest.xml",
             "assets/one_query_hash.txt","assets/params_map.txt","assets/params_map_v4_u0.txt","assets/params_names_v4_u0.txt"}

entries = []   # (key, bytes)
for f in COOKER_FILES:
    p = os.path.join(ROOT, "cooker", f)
    if not os.path.isfile(p): sys.exit("MISSING cooker template: "+p)
    entries.append(("cooker/"+f, open(p,"rb").read()))

z = zipfile.ZipFile(NUXD)
for n in z.namelist():
    if n in NUXD_DROP or n.startswith("META-INF/"): continue
    entries.append(("nuxd/"+n, z.read(n)))

# pack into one blob + table, then zlib-compress the blob
blob = bytearray(); table = []
for key, data in entries:
    table.append((key, len(blob), len(data))); blob += data
comp = zlib.compress(bytes(blob), 9)
print("embedded: %d files, blob=%d bytes, compressed=%d bytes" % (len(entries), len(blob), len(comp)))

with open(os.path.join(OUT,"embedded_assets.h"),"w") as h:
    h.write("// AUTO-GENERATED by cooker/gen_embedded_assets.py — do not edit.\n#pragma once\n"
            "#include <vector>\n#include <string>\n#include <cstdint>\n#include <utility>\n"
            "namespace embassets {\n"
            "// cooker/*.bin template by its readFileBytes path; returns false if not embedded.\n"
            "bool get(const std::string& name, std::vector<uint8_t>& out);\n"
            "// the Nuxd donor files (archive name -> bytes) spliceAPK rebuilds the shell from.\n"
            "std::vector<std::pair<std::string,std::vector<uint8_t>>> nuxdDonor();\n"
            "}\n")

with open(os.path.join(OUT,"embedded_assets.cpp"),"w") as c:
    c.write('// AUTO-GENERATED by cooker/gen_embedded_assets.py — do not edit.\n'
            '#include "cook/embedded_assets.h"\n#include "miniz.h"\n#include <mutex>\n#include <cstring>\n')
    c.write("static const unsigned char ZBLOB[]={")
    c.write(",".join(str(b) for b in comp))
    c.write("};\n")
    c.write("static const unsigned ZLEN=%d; static const unsigned RAWLEN=%d;\n" % (len(comp), len(blob)))
    c.write("struct E{const char* n; unsigned off,len;};\n")
    c.write("static const E TBL[]={")
    c.write(",".join('{"%s",%d,%d}'%(k,o,l) for (k,o,l) in table))
    c.write("};\nstatic const unsigned NTBL=%d;\n" % len(table))
    c.write(
"static std::vector<uint8_t> g_blob; static std::once_flag g_once;\n"
"static void ensure(){ std::call_once(g_once, [](){ g_blob.resize(RAWLEN); mz_ulong dl=RAWLEN;\n"
"  mz_uncompress(g_blob.data(), &dl, ZBLOB, ZLEN); }); }\n"
"namespace embassets {\n"
"bool get(const std::string& name, std::vector<uint8_t>& out){ ensure();\n"
"  for(unsigned i=0;i<NTBL;i++) if(name==TBL[i].n){ out.assign(g_blob.begin()+TBL[i].off, g_blob.begin()+TBL[i].off+TBL[i].len); return true; } return false; }\n"
"std::vector<std::pair<std::string,std::vector<uint8_t>>> nuxdDonor(){ ensure(); std::vector<std::pair<std::string,std::vector<uint8_t>>> r;\n"
"  const char* pfx=\"nuxd/\"; for(unsigned i=0;i<NTBL;i++){ std::string n=TBL[i].n; if(n.rfind(pfx,0)==0) r.push_back({n.substr(5), std::vector<uint8_t>(g_blob.begin()+TBL[i].off, g_blob.begin()+TBL[i].off+TBL[i].len)}); } return r; }\n"
"}\n")
print("wrote", os.path.join(OUT,"embedded_assets.cpp"), "and .h")
