// AUTO-GENERATED by cooker/gen_embedded_assets.py — do not edit.
#pragma once
#include <vector>
#include <string>
#include <cstdint>
#include <utility>
namespace embassets {
// cooker/*.bin template by its readFileBytes path; returns false if not embedded.
bool get(const std::string& name, std::vector<uint8_t>& out);
// the Nuxd donor files (archive name -> bytes) spliceAPK rebuilds the shell from.
std::vector<std::pair<std::string,std::vector<uint8_t>>> nuxdDonor();
}
